language: php

matrix:
  include:
    - php: 5.6
      env: PHPUNIT_VERSION=5.6.*
      dist: trusty
    - php: 7.0
      env: PHPUNIT_VERSION=5.6.*
      dist: trusty
    - php: 7.1
      env: PHPUNIT_VERSION=5.7.*
      dist: trusty
    - php: 7.2
      env: PHPUNIT_VERSION=8.5.*
      dist: bionic
    - php: 7.3
      env: PHPUNIT_VERSION=9.5.*
      dist: bionic
    - php: 7.4
      env: PHPUNIT_VERSION=9.5.*
      dist: bionic
    - php: 8.0
      env: PHPUNIT_VERSION=9.5.*
      dist: bionic

sudo: false

before_script:
    - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update
    - composer update --prefer-dist

script:
    - phpunit TestRunner.php .

