language: php

# dist: trusty

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0

env:
  - PHPUNIT_VERSION=5.6.*

matrix:
  include:
    - php: 5.6
      env: PHPUNIT_VERSION=5.6.*
    - php: 7.0
      env: PHPUNIT_VERSION=6.5.*
    - php: 7.1
      env: PHPUNIT_VERSION=7.5.*
    - php: 7.2
      env: PHPUNIT_VERSION=8.5.*
    - php: 7.3
      env: PHPUNIT_VERSION=9.5.*
    - php: 7.4
      env: PHPUNIT_VERSION=9.5.*
    - php: 8.0
      env: PHPUNIT_VERSION=9.5.*

sudo: false

before_script:
    - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update
    - composer update --prefer-dist

script:
    - phpunit TestRunner.php .

